# Generated by Django 4.2.6 on 2023-10-11 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=250)),
                ('images', models.ImageField(upload_to='pictures1')),
                ('description', models.TextField()),
            ],
        ),
    ]
